# Generated by Django 2.2.26 on 2022-08-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mfa", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lockeduser",
            options={
                "ordering": ("local__last_name", "local__first_name"),
                "permissions": (("unlock", "Can unlock users for enrollment"),),
            },
        ),
    ]
