# Generated by Django 2.2.28 on 2024-03-28 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.utils
import outpost.django.base.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mfa", "0002_auto_20220825_1546"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnlockEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to=outpost.django.base.utils.Uuid4Upload,
                        validators=[
                            outpost.django.base.validators.FileValidator(
                                mimetypes=["image/png"]
                            )
                        ],
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
