# Generated by Django 2.2.28 on 2024-04-10 19:25

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mfa", "0003_unlockevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnlockNetwork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("inet", netfields.fields.CidrAddressField(max_length=43)),
            ],
        ),
    ]
